/**
 * Created by 1 on 2016/1/1.
 */

export const LOGIN = "LOGIN"
export const LOGINOUT = "LOGINOUT"
export const INITIAL = "INITIAL"
export const GETSPLIST = "GETSPLIST"
export const GETGALLERYLIST = "GETGALLERYLIST"
export const GETVEDIOLIST = "GETVEDIOLIST"
export const UPLOADINGVEDIO = "UPLOADINGVEDIO"
export const UPLOADINGAUDIO = "UPLOADINGAUDIO"
export const GETDOCUMENTLIST = "GETDOCUMENTLIST"
export const GETAUDIOLIST = "GETAUDIOLIST"
export const UPDATEMENU = "UPDATEMENU"
